# Copyright 2017 The Chenmich Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
import unittest
import csv
import pathlib
import numpy as np
import large_data_preparation as ldp
''' Test large-data-preparation module
'''
class test_make_example(unittest.TestCase):
    ''' Test _make_example function in the large_data_preparation module
    '''
    def test_examples(self):
        ''' Test the examples generated by function _make_examples
        '''
        filename = 'data/raw_data/some00000.csv'
        lines = np.arange(20000).reshape(4000, 5)
        sequence_length = 200
        length = len(lines)
        examples = ldp._make_examples(200, lines[sequence_length:])
        _num_example = len(lines[sequence_length:]) // (2*sequence_length) + 1
        length = len(examples)
        self.assertEqual(length, 2*_num_example)
        _tmp = examples[2*(_num_example - 1)]
        self.assertEqual(len(_tmp), sequence_length // 2)
        self.assertEqual(len(examples[2*_num_example - 1]), sequence_length //2)
#
class test_save_example(unittest.TestCase):
    ''' Test _save_examples function in the large_data_preparation module
    '''
    pass
#
class test_combinate_examples(unittest.TestCase):
    def test_combinate_examples(self):
        examples = np.arange(10000).reshape(2000, 5).tolist()
        _examples = np.arange(2000).reshape(400, 5).tolist()
        #test result of combination
        _length = len(examples)
        _other_length = len(_examples)
        ldp._combinate_example(examples, _examples)
        total_length = len(examples)
        self.assertEqual(total_length, _length + _other_length)
        #test parameter
        with self.assertRaises(ValueError) as context:
            ldp._combinate_example(examples, 2)
            ldp._combinate_example(3, _examples)
            ldp._combinate_example(3.0, 2.0)

#
class test_get_file_list(unittest.TestCase):
    def test_result(self):
        path = 'data/raw_data'
        _extension = '*.csv'
        files = ldp._get_file_list(path, _extension)
        length = len(list(files))
        self.assertGreater(length, 0)
#
class test_save_examples(unittest.TestCase):
    def test_save_exampes(self):
        pass

if __name__ == "__main__":
    unittest.main()
